dvd_rental:
  target: dev
  outputs:
    dev:
      type: postgres
      host: on-boarding-de.cphyvakixbqr.us-east-1.rds.amazonaws.com
      user: dbt_user
      password: DyFVezsKR9HdN9v8
      port: 5432
      dbname: dvdrental
      schema: steven_dbt_schema
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
